version: "3.3"

services:
    
    DSKTOOL:
        container_name: DSKTOOL
        image: blackboardhub.ddns.net/bbdn/oscelot-dsktool:1.0
        ports:
            - "8000:8000"
        networks:
            - dsktool
        restart: unless-stopped
        environment:
            DJANGO_DEBUG: "True" #May set to False
            #https://miniwebtool.com/django-secret-key-generator/
            SECRET_KEY: "gd4owr7x-()dv)gh!2s-un9!y-6bb(iv!m2n0!=c32mt0+xbv!" #eventually use docker secrets...
            DJANGO_ALLOWED_HOSTS: 127.0.0.1 localhost .ngrok.io
            BLACKBOARD_LEARN_INSTANCE: "your Learn FQDN no protocol e.g. my.learn.server.com"
            APPLICATION_KEY: "your application key"
            APPLICATION_SECRET: "your application secret"

networks:
    dsktool:
        driver: bridge
